sonata_admin:
    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        #role_admin: IS_AUTHENTICATED_ANONYMOUSLY
        role_super_admin: ROLE_SUPER_ADMIN
        
    title: 'Portail Web Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    
    templates:
        edit:              '@SonataAdmin/CRUD/edit.html.twig'
        tab_menu_template: '@SonataAdmin/Core/tab_menu_template.html.twig'        
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
