vich_uploader:
    db_driver: orm
    mappings:
        laboratoire_image:
            uri_prefix: /uploads/images/laboratoire
            upload_destination: '%kernel.project_dir%/public/uploads/images/laboratoire'

        responsable_image:
            uri_prefix: /uploads/images/responsable
            upload_destination: '%kernel.project_dir%/public/uploads/images/responsable'

        association_image:
            uri_prefix: /uploads/images/association
            upload_destination: '%kernel.project_dir%/public/uploads/images/association'

        partenaire_image:
            uri_prefix: /uploads/images/partenaire
            upload_destination: '%kernel.project_dir%/public/uploads/images/partenaire' 

        departement_image:
            uri_prefix: /uploads/images/departement
            upload_destination: '%kernel.project_dir%/public/uploads/images/departement'

        laureat_image:
            uri_prefix: /uploads/images/laureat
            upload_destination: '%kernel.project_dir%/public/uploads/images/laureat'
            
        article_image:
            uri_prefix: /uploads/images/article
            upload_destination: '%kernel.project_dir%/public/uploads/images/article'

        fichier_image:
            uri_prefix: /uploads/pdfs/fichier
            upload_destination: '%kernel.project_dir%/public/uploads/pdfs/fichier'

        depliant_pdf:
            uri_prefix: /uploads/pdfs/depliant
            upload_destination: '%kernel.project_dir%/public/uploads/pdfs/depliant'

        responsable_cv:
            uri_prefix: /uploads/pdfs/cv
            upload_destination: '%kernel.project_dir%/public/uploads/pdfs/cv'  

       
#            upload_destination: '%kernel.project_dir%/public/uploads/pdfs/rapport'                   
#            inject_on_load: false
#            delete_on_update: true
#            delete_on_remove: true




